title: Krishna Chaithanya Marripati
email: hello@kmarrip.co
description: >-
  "This is the portfolio website, I will be documenting everything
   I learn over time here, cheerThis is the portfolio website, I will be documenting everything
   I learn over time here, cheers."

baseurl: ""
url: ""

theme: minima
plugins:
  - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
